# Generated by Django 5.0.3 on 2024-06-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_event', models.DateTimeField(auto_now_add=True)),
                ('data_start_date', models.DateField()),
                ('data_end_date', models.DateField()),
                ('total_uplift_in_lts_occ', models.FloatField()),
                ('total_uplift_in_lts_ven', models.FloatField()),
                ('total_selisih', models.FloatField()),
                ('fuel_agent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MissingInvoiceInVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('flight', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('departure', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('arrival', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('registration', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('uplift_in_lts', models.FloatField(blank=True, default=0, null=True)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fuel_agent', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_invoices_in_vendor', to='reconapp.result')),
            ],
        ),
        migrations.CreateModel(
            name='DetailResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_occ', models.DateField()),
                ('flight_occ', models.CharField(max_length=100)),
                ('departure_occ', models.CharField(max_length=100)),
                ('arrival_occ', models.CharField(max_length=100)),
                ('registration_occ', models.CharField(max_length=100)),
                ('uplift_in_lts_occ', models.FloatField(default=0)),
                ('date_ven', models.DateField()),
                ('flight_ven', models.CharField(max_length=100)),
                ('departure_ven', models.CharField(max_length=100)),
                ('arrival_ven', models.CharField(max_length=100)),
                ('registration_ven', models.CharField(max_length=100)),
                ('uplift_in_lts_ven', models.FloatField(default=0)),
                ('invoice_no', models.CharField(max_length=100)),
                ('fuel_agent', models.CharField(max_length=100)),
                ('selisih', models.FloatField(default=0)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_results', to='reconapp.result')),
            ],
        ),
    ]
