# Generated by Django 5.0.3 on 2024-06-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuelIaa',
        ),
    ]
