# Generated by Django 5.0.3 on 2024-06-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occapp', '0004_delete_fueliaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelIaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Flight', models.CharField(max_length=50)),
                ('Dep', models.CharField(max_length=100)),
                ('Arr', models.CharField(max_length=100)),
                ('Reg', models.CharField(max_length=20)),
                ('Uplift_in_Lts', models.FloatField()),
                ('Invoice', models.CharField(max_length=100, unique=True)),
                ('Vendor', models.CharField(max_length=150)),
            ],
        ),
    ]
