# Generated by Django 5.0.3 on 2024-06-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuelAgentName',
            new_name='AgentName',
        ),
    ]
