# Generated by Django 5.0.3 on 2024-06-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0002_rename_fuelagentname_agentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentname',
            name='fuel_agent_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
